default:
  tempfiles: /tmp/frr-mad
  exportpath: /tmp/frr-mad/exports
  logpath: /var/log/frr-mad
  debuglevel: none 

socket:
  unixsocketlocation: /var/run/frr-mad
  unixsocketname: analyzer.sock
  sockettype: unix

analyzer:
  foo: bar

aggregator:
  frrmetricsurl: http://localhost:9342/metrics
  frrconfigpath: /etc/frr/frr.conf
  pollinterval: 5
  socketpathbgp: /var/run/frr/bgpd.vty
  socketpathospf: /var/run/frr/ospfd.vty
  socketpathzebra: /var/run/frr/zebra.vty
  socketpath: /var/run/frr

exporter:
  Port: 9091
  OSPFRouterData: (collector.ospf.router,"Collect OSPF router information metrics",true)
  OSPFNetworkData: (collector.ospf.network,"Collect OSPF network information metrics",true)
  OSPFSummaryData: (collector.ospf.summary,"Collect OSPF summary information metrics",true)
  OSPFAsbrSummaryData: (collector.ospf.asbr-summary,"Collect OSPF ASBR summary information metrics",true)
  OSPFExternalData: (collector.ospf.external,"Collect OSPF external route information metrics",true)
  OSPFNssaExternalData: (collector.ospf.nssa-external,"Collect OSPF NSSA external route information metrics",true)
  OSPFDatabase: (collector.ospf.database,"Collect OSPF database information metrics",true)
  OSPFNeighbors: (collector.ospf.neighbors,"Collect OSPF neighbor information metrics",true)
  InterfaceList: (collector.interface.list,"Collect interface list information metrics",true)
  RouteList: (collector.route.list,"Collect route list information metrics",true)
