services:
  # Router nodes
  r101:
    image: frr-854-dev
    container_name: r101
    volumes:
      - ./r101/daemons:/etc/frr/daemons
      - ./r101/frr.conf:/etc/frr/frr.conf
      - ./r101/vtysh.conf:/etc/frr/vtysh.conf
      - ../src:/app/src
      - ../local:/app/local
      - ../protobufSource:/app/protobufSource
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r102:
    image: frr-854
    container_name: r102
    volumes:
      - ./r102/daemons:/etc/frr/daemons
      - ./r102/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r103:
    image: frr-854
    container_name: r103
    volumes:
      - ./r103/daemons:/etc/frr/daemons
      - ./r103/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  cr104:
    image: frr-854
    container_name: cr104
    volumes:
      - ./cr104/daemons:/etc/frr/daemons
      - ./cr104/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  cr105:
    image: frr-854
    container_name: cr105
    volumes:
      - ./cr105/daemons:/etc/frr/daemons
      - ./cr105/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  cr106:
    image: frr-854
    container_name: cr106
    volumes:
      - ./cr106/daemons:/etc/frr/daemons
      - ./cr106/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  cr107:
    image: frr-854
    container_name: cr107
    volumes:
      - ./cr107/daemons:/etc/frr/daemons
      - ./cr107/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  cr108:
    image: frr-854
    container_name: cr108
    volumes:
      - ./cr108/daemons:/etc/frr/daemons
      - ./cr108/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  cr109:
    image: frr-854
    container_name: cr109
    volumes:
      - ./cr109/daemons:/etc/frr/daemons
      - ./cr109/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r111:
    image: frr-854
    container_name: r111
    volumes:
      - ./r111/daemons:/etc/frr/daemons
      - ./r111/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r112:
    image: frr-854
    container_name: r112
    volumes:
      - ./r112/daemons:/etc/frr/daemons
      - ./r112/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r121:
    image: frr-854
    container_name: r121
    volumes:
      - ./r121/daemons:/etc/frr/daemons
      - ./r121/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r122:
    image: frr-854
    container_name: r122
    volumes:
      - ./r122/daemons:/etc/frr/daemons
      - ./r122/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r131:
    image: frr-854
    container_name: r131
    volumes:
      - ./r131/daemons:/etc/frr/daemons
      - ./r131/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r191:
    image: frr-854
    container_name: r191
    volumes:
      - ./r191/daemons:/etc/frr/daemons
      - ./r191/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r201:
    image: frr-854
    container_name: r201
    volumes:
      - ./r201/daemons:/etc/frr/daemons
      - ./r201/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r202:
    image: frr-854
    container_name: r202
    volumes:
      - ./r202/daemons:/etc/frr/daemons
      - ./r202/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r301:
    image: frr-854
    container_name: r301
    volumes:
      - ./r301/daemons:/etc/frr/daemons
      - ./r301/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r302:
    image: frr-854
    container_name: r302
    volumes:
      - ./r302/daemons:/etc/frr/daemons
      - ./r302/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  r391:
    image: frr-854
    container_name: r391
    volumes:
      - ./r391/daemons:/etc/frr/daemons
      - ./r391/frr.conf:/etc/frr/frr.conf
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN

  # PC nodes
  pc101:
    image: praqma/network-multitool:latest
    container_name: pc101
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  cpc104:
    image: praqma/network-multitool:latest
    container_name: cpc104
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  cpc105:
    image: praqma/network-multitool:latest
    container_name: cpc105
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  cpc106:
    image: praqma/network-multitool:latest
    container_name: cpc106
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  cpc107:
    image: praqma/network-multitool:latest
    container_name: cpc107
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  cpc108:
    image: praqma/network-multitool:latest
    container_name: cpc108
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  cpc109:
    image: praqma/network-multitool:latest
    container_name: cpc109
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc111:
    image: praqma/network-multitool:latest
    container_name: pc111
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc121:
    image: praqma/network-multitool:latest
    container_name: pc121
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc131:
    image: praqma/network-multitool:latest
    container_name: pc131
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc191:
    image: praqma/network-multitool:latest
    container_name: pc191
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc201:
    image: praqma/network-multitool:latest
    container_name: pc201
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc301:
    image: praqma/network-multitool:latest
    container_name: pc301
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

  pc391:
    image: praqma/network-multitool:latest
    container_name: pc391
    networks:
      frr_network: {}
    cap_add:
      - NET_ADMIN

# Single network for all containers
networks:
  frr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16