// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protocol.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CombinedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ospf          *OSPFMetrics           `protobuf:"bytes,2,opt,name=ospf,proto3" json:"ospf,omitempty"`
	Config        *NetworkConfig         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

/*
Simple Payload:
- OSPFMetrics


Response Payload:
Command: asdf
Message: asdf
Payload: (e.g.) OSPFMetrics


Message Payload: TUI -> Analzyer
Service: OSPF
Command: Read
Package: Neighbors

Simple:
Response Payload: Analyzer -> TUI
Payload: OSPFNeihgbors


Extended:
Status: Success
Message: Successfully refreshed OSPFNeighbors stats
TimeStamp: Now
Payload: OSPFNeighbors


*/


func (x *CombinedState) Reset() {
	*x = CombinedState{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedState) ProtoMessage() {}

func (x *CombinedState) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedState.ProtoReflect.Descriptor instead.
func (*CombinedState) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *CombinedState) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CombinedState) GetOspf() *OSPFMetrics {
	if x != nil {
		return x.Ospf
	}
	return nil
}

func (x *CombinedState) GetConfig() *NetworkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CombinedState) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

type OSPFMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Neighbors       []*OSPFNeighbor        `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Routes          []*OSPFRoute           `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Interfaces      []*OSPFInterface       `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Lsas            []*OSPFlsa             `protobuf:"bytes,4,rep,name=lsas,proto3" json:"lsas,omitempty"`
	HasRouteChanges bool                   `protobuf:"varint,5,opt,name=has_route_changes,json=hasRouteChanges,proto3" json:"has_route_changes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OSPFMetrics) Reset() {
	*x = OSPFMetrics{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFMetrics) ProtoMessage() {}

func (x *OSPFMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFMetrics.ProtoReflect.Descriptor instead.
func (*OSPFMetrics) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *OSPFMetrics) GetNeighbors() []*OSPFNeighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *OSPFMetrics) GetRoutes() []*OSPFRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *OSPFMetrics) GetInterfaces() []*OSPFInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *OSPFMetrics) GetLsas() []*OSPFlsa {
	if x != nil {
		return x.Lsas
	}
	return nil
}

func (x *OSPFMetrics) GetHasRouteChanges() bool {
	if x != nil {
		return x.HasRouteChanges
	}
	return false
}

type OSPFNeighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Interface     string                 `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFNeighbor) Reset() {
	*x = OSPFNeighbor{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFNeighbor) ProtoMessage() {}

func (x *OSPFNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFNeighbor.ProtoReflect.Descriptor instead.
func (*OSPFNeighbor) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *OSPFNeighbor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSPFNeighbor) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OSPFNeighbor) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OSPFNeighbor) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *OSPFNeighbor) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type OSPFRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NextHop       string                 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	Cost          int32                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Area          string                 `protobuf:"bytes,6,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFRoute) Reset() {
	*x = OSPFRoute{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFRoute) ProtoMessage() {}

func (x *OSPFRoute) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFRoute.ProtoReflect.Descriptor instead.
func (*OSPFRoute) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *OSPFRoute) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *OSPFRoute) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *OSPFRoute) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *OSPFRoute) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *OSPFRoute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OSPFRoute) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type OSPFInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	NbrCount      int32                  `protobuf:"varint,3,opt,name=nbr_count,json=nbrCount,proto3" json:"nbr_count,omitempty"`
	NbrAdj        int32                  `protobuf:"varint,4,opt,name=nbr_adj,json=nbrAdj,proto3" json:"nbr_adj,omitempty"`
	Passive       bool                   `protobuf:"varint,5,opt,name=passive,proto3" json:"passive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFInterface) Reset() {
	*x = OSPFInterface{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFInterface) ProtoMessage() {}

func (x *OSPFInterface) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFInterface.ProtoReflect.Descriptor instead.
func (*OSPFInterface) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *OSPFInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSPFInterface) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *OSPFInterface) GetNbrCount() int32 {
	if x != nil {
		return x.NbrCount
	}
	return 0
}

func (x *OSPFInterface) GetNbrAdj() int32 {
	if x != nil {
		return x.NbrAdj
	}
	return 0
}

func (x *OSPFInterface) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

type OSPFlsa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LsId          string                 `protobuf:"bytes,2,opt,name=ls_id,json=lsId,proto3" json:"ls_id,omitempty"`
	AdvRouter     string                 `protobuf:"bytes,3,opt,name=adv_router,json=advRouter,proto3" json:"adv_router,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	Sequence	  string				 `protobuf:"bytes,6,opt,name=sequence,proto3" json:"sequence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFlsa) Reset() {
	*x = OSPFlsa{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFlsa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFlsa) ProtoMessage() {}

func (x *OSPFlsa) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFlsa.ProtoReflect.Descriptor instead.
func (*OSPFlsa) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *OSPFlsa) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OSPFlsa) GetLsId() string {
	if x != nil {
		return x.LsId
	}
	return ""
}

func (x *OSPFlsa) GetAdvRouter() string {
	if x != nil {
		return x.AdvRouter
	}
	return ""
}

func (x *OSPFlsa) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *OSPFlsa) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *OSPFlsa) GetASequence() string {
	if x != nil {
		return x.Sequence
	}
	return ""
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Areas         []*OSPFArea            `protobuf:"bytes,2,rep,name=areas,proto3" json:"areas,omitempty"`
	Interfaces    []*OSPFInterfaceConfig `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *NetworkConfig) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *NetworkConfig) GetAreas() []*OSPFArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *NetworkConfig) GetInterfaces() []*OSPFInterfaceConfig {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type OSPFArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Networks      []string               `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFArea) Reset() {
	*x = OSPFArea{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFArea) ProtoMessage() {}

func (x *OSPFArea) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFArea.ProtoReflect.Descriptor instead.
func (*OSPFArea) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *OSPFArea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSPFArea) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type OSPFInterfaceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`
	Passive       bool                   `protobuf:"varint,4,opt,name=passive,proto3" json:"passive,omitempty"`
	Cost          int32                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFInterfaceConfig) Reset() {
	*x = OSPFInterfaceConfig{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFInterfaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFInterfaceConfig) ProtoMessage() {}

func (x *OSPFInterfaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFInterfaceConfig.ProtoReflect.Descriptor instead.
func (*OSPFInterfaceConfig) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *OSPFInterfaceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSPFInterfaceConfig) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *OSPFInterfaceConfig) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *OSPFInterfaceConfig) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *OSPFInterfaceConfig) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type SystemMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	NetworkStats  []*InterfaceStats      `protobuf:"bytes,3,rep,name=network_stats,json=networkStats,proto3" json:"network_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetNetworkStats() []*InterfaceStats {
	if x != nil {
		return x.NetworkStats
	}
	return nil
}

type InterfaceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,4,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,5,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	OperState     string                 `protobuf:"bytes,6,opt,name=oper_state,json=operState,proto3" json:"oper_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStats) Reset() {
	*x = InterfaceStats{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStats) ProtoMessage() {}

func (x *InterfaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStats.ProtoReflect.Descriptor instead.
func (*InterfaceStats) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *InterfaceStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceStats) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *InterfaceStats) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *InterfaceStats) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\n" +
	"aggregator\x1a\x1fgoogle/protobuf/timestamp.proto\"\xdc\x01\n" +
	"\rCombinedState\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12+\n" +
	"\x04ospf\x18\x02 \x01(\v2\x17.aggregator.OSPFMetricsR\x04ospf\x121\n" +
	"\x06config\x18\x03 \x01(\v2\x19.aggregator.NetworkConfigR\x06config\x121\n" +
	"\x06system\x18\x04 \x01(\v2\x19.aggregator.SystemMetricsR\x06system\"\x84\x02\n" +
	"\vOSPFMetrics\x126\n" +
	"\tneighbors\x18\x01 \x03(\v2\x18.aggregator.OSPFNeighborR\tneighbors\x12-\n" +
	"\x06routes\x18\x02 \x03(\v2\x15.aggregator.OSPFRouteR\x06routes\x129\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x19.aggregator.OSPFInterfaceR\n" +
	"interfaces\x12'\n" +
	"\x04lsas\x18\x04 \x03(\v2\x13.aggregator.OSPFlsaR\x04lsas\x12*\n" +
	"\x11has_route_changes\x18\x05 \x01(\bR\x0fhasRouteChanges\"v\n" +
	"\fOSPFNeighbor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\"\x98\x01\n" +
	"\tOSPFRoute\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\tR\anextHop\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\x06 \x01(\tR\x04area\"\x87\x01\n" +
	"\rOSPFInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\x12\x1b\n" +
	"\tnbr_count\x18\x03 \x01(\x05R\bnbrCount\x12\x17\n" +
	"\anbr_adj\x18\x04 \x01(\x05R\x06nbrAdj\x12\x18\n" +
	"\apassive\x18\x05 \x01(\bR\apassive\"w\n" +
	"\aOSPFlsa\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x13\n" +
	"\x05ls_id\x18\x02 \x01(\tR\x04lsId\x12\x1d\n" +
	"\n" +
	"adv_router\x18\x03 \x01(\tR\tadvRouter\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\"\x99\x01\n" +
	"\rNetworkConfig\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12*\n" +
	"\x05areas\x18\x02 \x03(\v2\x14.aggregator.OSPFAreaR\x05areas\x12?\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x1f.aggregator.OSPFInterfaceConfigR\n" +
	"interfaces\"6\n" +
	"\bOSPFArea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnetworks\x18\x02 \x03(\tR\bnetworks\"k\n" +
	"\x13OSPFInterfaceConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\x12\x18\n" +
	"\apassive\x18\x03 \x01(\bR\apassive\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\"\x90\x01\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12?\n" +
	"\rnetwork_stats\x18\x03 \x03(\v2\x1a.aggregator.InterfaceStatsR\fnetworkStats\"\xb3\x01\n" +
	"\x0eInterfaceStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1b\n" +
	"\trx_errors\x18\x04 \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\x05 \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"oper_state\x18\x06 \x01(\tR\toperStateB.Z,github.com/ba2025-ysmprc/frr-tui/backend/pkgb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_protocol_proto_goTypes = []any{
	(*CombinedState)(nil),         // 0: aggregator.CombinedState
	(*OSPFMetrics)(nil),           // 1: aggregator.OSPFMetrics
	(*OSPFNeighbor)(nil),          // 2: aggregator.OSPFNeighbor
	(*OSPFRoute)(nil),             // 3: aggregator.OSPFRoute
	(*OSPFInterface)(nil),         // 4: aggregator.OSPFInterface
	(*OSPFlsa)(nil),               // 5: aggregator.OSPFlsa
	(*NetworkConfig)(nil),         // 6: aggregator.NetworkConfig
	(*OSPFArea)(nil),              // 7: aggregator.OSPFArea
	(*OSPFInterfaceConfig)(nil),   // 8: aggregator.OSPFInterfaceConfig
	(*SystemMetrics)(nil),         // 9: aggregator.SystemMetrics
	(*InterfaceStats)(nil),        // 10: aggregator.InterfaceStats
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_protocol_proto_depIdxs = []int32{
	11, // 0: aggregator.CombinedState.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 1: aggregator.CombinedState.ospf:type_name -> aggregator.OSPFMetrics
	6,  // 2: aggregator.CombinedState.config:type_name -> aggregator.NetworkConfig
	9,  // 3: aggregator.CombinedState.system:type_name -> aggregator.SystemMetrics
	2,  // 4: aggregator.OSPFMetrics.neighbors:type_name -> aggregator.OSPFNeighbor
	3,  // 5: aggregator.OSPFMetrics.routes:type_name -> aggregator.OSPFRoute
	4,  // 6: aggregator.OSPFMetrics.interfaces:type_name -> aggregator.OSPFInterface
	5,  // 7: aggregator.OSPFMetrics.lsas:type_name -> aggregator.OSPFlsa
	7,  // 8: aggregator.NetworkConfig.areas:type_name -> aggregator.OSPFArea
	8,  // 9: aggregator.NetworkConfig.interfaces:type_name -> aggregator.OSPFInterfaceConfig
	10, // 10: aggregator.SystemMetrics.network_stats:type_name -> aggregator.InterfaceStats
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}

