root = "/app/src"
tmp_dir = "/app/tmp"

[build]
cmd = "cd /app/src/backend && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-s' -tags=docker -o /app/tmp/analyzer_frr ./cmd/frr-analyzer && cd /app/src/frontend && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags='-s' -tags=docker -o /app/tmp/frr-tui ./cmd/tui"
bin = "/app/tmp/analyzer_frr"
full_bin = "app/tmp/analyzer_frr stop && /app/tmp/analyzer_frr start"
delay = 500
exclude_dir = ["tmp", "vendor"]
include_ext = ["go", "proto", "yaml", "yml", "json", "toml", "css", "js", "html", "md", "conf"]
exclude_file = []
exclude_regex = ["_test\\.go"]
recursive = true

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[screen]
clear_on_rebuild = true

[misc]
clean_on_exit = true
