// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: protocol.proto

package pkg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Message represents the top-level message structure
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Package       string                 `protobuf:"bytes,2,opt,name=package,proto3" json:"package,omitempty"`
	Params        map[string]*Value      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protocol_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *Message) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Message) GetParams() map[string]*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

// Command represents a specific command
type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Package       string                 `protobuf:"bytes,1,opt,name=package,proto3" json:"package,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	Params        map[string]*Value      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_protocol_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetPackage() string {
	if x != nil {
		return x.Package
	}
	return ""
}

func (x *Command) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *Command) GetParams() map[string]*Value {
	if x != nil {
		return x.Params
	}
	return nil
}

// Response represents the server's response
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data          *Value                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_protocol_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{2}
}

func (x *Response) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Response) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Response) GetData() *Value {
	if x != nil {
		return x.Data
	}
	return nil
}

// Value represents a dynamic value (similar to interface{} in Go)
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_StringValue
	//	*Value_IntValue
	//	*Value_DoubleValue
	//	*Value_BoolValue
	//	*Value_StructValue
	//	*Value_ListValue
	//	*Value_BytesValue
	//	*Value_CombinedState
	//	*Value_OspfMetrics
	//	*Value_OspfNeighbor
	//	*Value_OspfRoute
	//	*Value_OspfInterface
	//	*Value_OspfLsa
	//	*Value_NetworkConfig
	//	*Value_OspfArea
	//	*Value_OspfInterfaceConfig
	//	*Value_SystemMetrics
	//	*Value_InterfaceStats
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_protocol_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{3}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStructValue() *Struct {
	if x != nil {
		if x, ok := x.Kind.(*Value_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetCombinedState() *CombinedState {
	if x != nil {
		if x, ok := x.Kind.(*Value_CombinedState); ok {
			return x.CombinedState
		}
	}
	return nil
}

func (x *Value) GetOspfMetrics() *OSPFMetrics {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfMetrics); ok {
			return x.OspfMetrics
		}
	}
	return nil
}

func (x *Value) GetOspfNeighbor() *OSPFNeighbor {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfNeighbor); ok {
			return x.OspfNeighbor
		}
	}
	return nil
}

func (x *Value) GetOspfRoute() *OSPFRoute {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfRoute); ok {
			return x.OspfRoute
		}
	}
	return nil
}

func (x *Value) GetOspfInterface() *OSPFInterface {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfInterface); ok {
			return x.OspfInterface
		}
	}
	return nil
}

func (x *Value) GetOspfLsa() *OSPFlsa {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfLsa); ok {
			return x.OspfLsa
		}
	}
	return nil
}

func (x *Value) GetNetworkConfig() *NetworkConfig {
	if x != nil {
		if x, ok := x.Kind.(*Value_NetworkConfig); ok {
			return x.NetworkConfig
		}
	}
	return nil
}

func (x *Value) GetOspfArea() *OSPFArea {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfArea); ok {
			return x.OspfArea
		}
	}
	return nil
}

func (x *Value) GetOspfInterfaceConfig() *OSPFInterfaceConfig {
	if x != nil {
		if x, ok := x.Kind.(*Value_OspfInterfaceConfig); ok {
			return x.OspfInterfaceConfig
		}
	}
	return nil
}

func (x *Value) GetSystemMetrics() *SystemMetrics {
	if x != nil {
		if x, ok := x.Kind.(*Value_SystemMetrics); ok {
			return x.SystemMetrics
		}
	}
	return nil
}

func (x *Value) GetInterfaceStats() *InterfaceStats {
	if x != nil {
		if x, ok := x.Kind.(*Value_InterfaceStats); ok {
			return x.InterfaceStats
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StructValue struct {
	StructValue *Struct `protobuf:"bytes,5,opt,name=struct_value,json=structValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,6,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,7,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_CombinedState struct {
	// Aggregator package message types
	CombinedState *CombinedState `protobuf:"bytes,8,opt,name=combined_state,json=combinedState,proto3,oneof"`
}

type Value_OspfMetrics struct {
	OspfMetrics *OSPFMetrics `protobuf:"bytes,9,opt,name=ospf_metrics,json=ospfMetrics,proto3,oneof"`
}

type Value_OspfNeighbor struct {
	OspfNeighbor *OSPFNeighbor `protobuf:"bytes,10,opt,name=ospf_neighbor,json=ospfNeighbor,proto3,oneof"`
}

type Value_OspfRoute struct {
	OspfRoute *OSPFRoute `protobuf:"bytes,11,opt,name=ospf_route,json=ospfRoute,proto3,oneof"`
}

type Value_OspfInterface struct {
	OspfInterface *OSPFInterface `protobuf:"bytes,12,opt,name=ospf_interface,json=ospfInterface,proto3,oneof"`
}

type Value_OspfLsa struct {
	OspfLsa *OSPFlsa `protobuf:"bytes,13,opt,name=ospf_lsa,json=ospfLsa,proto3,oneof"`
}

type Value_NetworkConfig struct {
	NetworkConfig *NetworkConfig `protobuf:"bytes,14,opt,name=network_config,json=networkConfig,proto3,oneof"`
}

type Value_OspfArea struct {
	OspfArea *OSPFArea `protobuf:"bytes,15,opt,name=ospf_area,json=ospfArea,proto3,oneof"`
}

type Value_OspfInterfaceConfig struct {
	OspfInterfaceConfig *OSPFInterfaceConfig `protobuf:"bytes,16,opt,name=ospf_interface_config,json=ospfInterfaceConfig,proto3,oneof"`
}

type Value_SystemMetrics struct {
	SystemMetrics *SystemMetrics `protobuf:"bytes,17,opt,name=system_metrics,json=systemMetrics,proto3,oneof"`
}

type Value_InterfaceStats struct {
	InterfaceStats *InterfaceStats `protobuf:"bytes,18,opt,name=interface_stats,json=interfaceStats,proto3,oneof"`
}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_IntValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_StructValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_CombinedState) isValue_Kind() {}

func (*Value_OspfMetrics) isValue_Kind() {}

func (*Value_OspfNeighbor) isValue_Kind() {}

func (*Value_OspfRoute) isValue_Kind() {}

func (*Value_OspfInterface) isValue_Kind() {}

func (*Value_OspfLsa) isValue_Kind() {}

func (*Value_NetworkConfig) isValue_Kind() {}

func (*Value_OspfArea) isValue_Kind() {}

func (*Value_OspfInterfaceConfig) isValue_Kind() {}

func (*Value_SystemMetrics) isValue_Kind() {}

func (*Value_InterfaceStats) isValue_Kind() {}

// Struct represents a map of string to Value (similar to map[string]interface{})
type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_protocol_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{4}
}

func (x *Struct) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

// ListValue represents a list of Values (similar to []interface{})
type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_protocol_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{5}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type CombinedState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Ospf          *OSPFMetrics           `protobuf:"bytes,2,opt,name=ospf,proto3" json:"ospf,omitempty"`
	Config        *NetworkConfig         `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	System        *SystemMetrics         `protobuf:"bytes,4,opt,name=system,proto3" json:"system,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CombinedState) Reset() {
	*x = CombinedState{}
	mi := &file_protocol_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CombinedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CombinedState) ProtoMessage() {}

func (x *CombinedState) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CombinedState.ProtoReflect.Descriptor instead.
func (*CombinedState) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{6}
}

func (x *CombinedState) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *CombinedState) GetOspf() *OSPFMetrics {
	if x != nil {
		return x.Ospf
	}
	return nil
}

func (x *CombinedState) GetConfig() *NetworkConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CombinedState) GetSystem() *SystemMetrics {
	if x != nil {
		return x.System
	}
	return nil
}

type OSPFMetrics struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Neighbors       []*OSPFNeighbor        `protobuf:"bytes,1,rep,name=neighbors,proto3" json:"neighbors,omitempty"`
	Routes          []*OSPFRoute           `protobuf:"bytes,2,rep,name=routes,proto3" json:"routes,omitempty"`
	Interfaces      []*OSPFInterface       `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	Lsas            []*OSPFlsa             `protobuf:"bytes,4,rep,name=lsas,proto3" json:"lsas,omitempty"`
	HasRouteChanges bool                   `protobuf:"varint,5,opt,name=has_route_changes,json=hasRouteChanges,proto3" json:"has_route_changes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OSPFMetrics) Reset() {
	*x = OSPFMetrics{}
	mi := &file_protocol_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFMetrics) ProtoMessage() {}

func (x *OSPFMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFMetrics.ProtoReflect.Descriptor instead.
func (*OSPFMetrics) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{7}
}

func (x *OSPFMetrics) GetNeighbors() []*OSPFNeighbor {
	if x != nil {
		return x.Neighbors
	}
	return nil
}

func (x *OSPFMetrics) GetRoutes() []*OSPFRoute {
	if x != nil {
		return x.Routes
	}
	return nil
}

func (x *OSPFMetrics) GetInterfaces() []*OSPFInterface {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

func (x *OSPFMetrics) GetLsas() []*OSPFlsa {
	if x != nil {
		return x.Lsas
	}
	return nil
}

func (x *OSPFMetrics) GetHasRouteChanges() bool {
	if x != nil {
		return x.HasRouteChanges
	}
	return false
}

type OSPFNeighbor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Interface     string                 `protobuf:"bytes,4,opt,name=interface,proto3" json:"interface,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFNeighbor) Reset() {
	*x = OSPFNeighbor{}
	mi := &file_protocol_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFNeighbor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFNeighbor) ProtoMessage() {}

func (x *OSPFNeighbor) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFNeighbor.ProtoReflect.Descriptor instead.
func (*OSPFNeighbor) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{8}
}

func (x *OSPFNeighbor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSPFNeighbor) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *OSPFNeighbor) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *OSPFNeighbor) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *OSPFNeighbor) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type OSPFRoute struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        string                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	NextHop       string                 `protobuf:"bytes,2,opt,name=next_hop,json=nextHop,proto3" json:"next_hop,omitempty"`
	Interface     string                 `protobuf:"bytes,3,opt,name=interface,proto3" json:"interface,omitempty"`
	Cost          int32                  `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Area          string                 `protobuf:"bytes,6,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFRoute) Reset() {
	*x = OSPFRoute{}
	mi := &file_protocol_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFRoute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFRoute) ProtoMessage() {}

func (x *OSPFRoute) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFRoute.ProtoReflect.Descriptor instead.
func (*OSPFRoute) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{9}
}

func (x *OSPFRoute) GetPrefix() string {
	if x != nil {
		return x.Prefix
	}
	return ""
}

func (x *OSPFRoute) GetNextHop() string {
	if x != nil {
		return x.NextHop
	}
	return ""
}

func (x *OSPFRoute) GetInterface() string {
	if x != nil {
		return x.Interface
	}
	return ""
}

func (x *OSPFRoute) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *OSPFRoute) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OSPFRoute) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type OSPFInterface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	NbrCount      int32                  `protobuf:"varint,3,opt,name=nbr_count,json=nbrCount,proto3" json:"nbr_count,omitempty"`
	NbrAdj        int32                  `protobuf:"varint,4,opt,name=nbr_adj,json=nbrAdj,proto3" json:"nbr_adj,omitempty"`
	Passive       bool                   `protobuf:"varint,5,opt,name=passive,proto3" json:"passive,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFInterface) Reset() {
	*x = OSPFInterface{}
	mi := &file_protocol_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFInterface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFInterface) ProtoMessage() {}

func (x *OSPFInterface) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFInterface.ProtoReflect.Descriptor instead.
func (*OSPFInterface) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{10}
}

func (x *OSPFInterface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSPFInterface) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *OSPFInterface) GetNbrCount() int32 {
	if x != nil {
		return x.NbrCount
	}
	return 0
}

func (x *OSPFInterface) GetNbrAdj() int32 {
	if x != nil {
		return x.NbrAdj
	}
	return 0
}

func (x *OSPFInterface) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

type OSPFlsa struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	LsId          string                 `protobuf:"bytes,2,opt,name=ls_id,json=lsId,proto3" json:"ls_id,omitempty"`
	AdvRouter     string                 `protobuf:"bytes,3,opt,name=adv_router,json=advRouter,proto3" json:"adv_router,omitempty"`
	Age           int32                  `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Area          string                 `protobuf:"bytes,5,opt,name=area,proto3" json:"area,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFlsa) Reset() {
	*x = OSPFlsa{}
	mi := &file_protocol_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFlsa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFlsa) ProtoMessage() {}

func (x *OSPFlsa) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFlsa.ProtoReflect.Descriptor instead.
func (*OSPFlsa) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{11}
}

func (x *OSPFlsa) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OSPFlsa) GetLsId() string {
	if x != nil {
		return x.LsId
	}
	return ""
}

func (x *OSPFlsa) GetAdvRouter() string {
	if x != nil {
		return x.AdvRouter
	}
	return ""
}

func (x *OSPFlsa) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *OSPFlsa) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

type NetworkConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouterId      string                 `protobuf:"bytes,1,opt,name=router_id,json=routerId,proto3" json:"router_id,omitempty"`
	Areas         []*OSPFArea            `protobuf:"bytes,2,rep,name=areas,proto3" json:"areas,omitempty"`
	Interfaces    []*OSPFInterfaceConfig `protobuf:"bytes,3,rep,name=interfaces,proto3" json:"interfaces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NetworkConfig) Reset() {
	*x = NetworkConfig{}
	mi := &file_protocol_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkConfig) ProtoMessage() {}

func (x *NetworkConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkConfig.ProtoReflect.Descriptor instead.
func (*NetworkConfig) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{12}
}

func (x *NetworkConfig) GetRouterId() string {
	if x != nil {
		return x.RouterId
	}
	return ""
}

func (x *NetworkConfig) GetAreas() []*OSPFArea {
	if x != nil {
		return x.Areas
	}
	return nil
}

func (x *NetworkConfig) GetInterfaces() []*OSPFInterfaceConfig {
	if x != nil {
		return x.Interfaces
	}
	return nil
}

type OSPFArea struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Networks      []string               `protobuf:"bytes,2,rep,name=networks,proto3" json:"networks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFArea) Reset() {
	*x = OSPFArea{}
	mi := &file_protocol_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFArea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFArea) ProtoMessage() {}

func (x *OSPFArea) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFArea.ProtoReflect.Descriptor instead.
func (*OSPFArea) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{13}
}

func (x *OSPFArea) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OSPFArea) GetNetworks() []string {
	if x != nil {
		return x.Networks
	}
	return nil
}

type OSPFInterfaceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Area          string                 `protobuf:"bytes,2,opt,name=area,proto3" json:"area,omitempty"`
	IpAddress     string                 `protobuf:"bytes,3,opt,name=IpAddress,proto3" json:"IpAddress,omitempty"`
	Passive       bool                   `protobuf:"varint,4,opt,name=passive,proto3" json:"passive,omitempty"`
	Cost          int32                  `protobuf:"varint,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OSPFInterfaceConfig) Reset() {
	*x = OSPFInterfaceConfig{}
	mi := &file_protocol_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OSPFInterfaceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OSPFInterfaceConfig) ProtoMessage() {}

func (x *OSPFInterfaceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OSPFInterfaceConfig.ProtoReflect.Descriptor instead.
func (*OSPFInterfaceConfig) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{14}
}

func (x *OSPFInterfaceConfig) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OSPFInterfaceConfig) GetArea() string {
	if x != nil {
		return x.Area
	}
	return ""
}

func (x *OSPFInterfaceConfig) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

func (x *OSPFInterfaceConfig) GetPassive() bool {
	if x != nil {
		return x.Passive
	}
	return false
}

func (x *OSPFInterfaceConfig) GetCost() int32 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type SystemMetrics struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	MemoryUsage   float64                `protobuf:"fixed64,2,opt,name=memory_usage,json=memoryUsage,proto3" json:"memory_usage,omitempty"`
	NetworkStats  []*InterfaceStats      `protobuf:"bytes,3,rep,name=network_stats,json=networkStats,proto3" json:"network_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemMetrics) Reset() {
	*x = SystemMetrics{}
	mi := &file_protocol_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemMetrics) ProtoMessage() {}

func (x *SystemMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemMetrics.ProtoReflect.Descriptor instead.
func (*SystemMetrics) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{15}
}

func (x *SystemMetrics) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *SystemMetrics) GetMemoryUsage() float64 {
	if x != nil {
		return x.MemoryUsage
	}
	return 0
}

func (x *SystemMetrics) GetNetworkStats() []*InterfaceStats {
	if x != nil {
		return x.NetworkStats
	}
	return nil
}

type InterfaceStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RxBytes       uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes       uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	RxErrors      uint64                 `protobuf:"varint,4,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
	TxErrors      uint64                 `protobuf:"varint,5,opt,name=tx_errors,json=txErrors,proto3" json:"tx_errors,omitempty"`
	OperState     string                 `protobuf:"bytes,6,opt,name=oper_state,json=operState,proto3" json:"oper_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterfaceStats) Reset() {
	*x = InterfaceStats{}
	mi := &file_protocol_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterfaceStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterfaceStats) ProtoMessage() {}

func (x *InterfaceStats) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterfaceStats.ProtoReflect.Descriptor instead.
func (*InterfaceStats) Descriptor() ([]byte, []int) {
	return file_protocol_proto_rawDescGZIP(), []int{16}
}

func (x *InterfaceStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InterfaceStats) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *InterfaceStats) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *InterfaceStats) GetRxErrors() uint64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

func (x *InterfaceStats) GetTxErrors() uint64 {
	if x != nil {
		return x.TxErrors
	}
	return 0
}

func (x *InterfaceStats) GetOperState() string {
	if x != nil {
		return x.OperState
	}
	return ""
}

var File_protocol_proto protoreflect.FileDescriptor

const file_protocol_proto_rawDesc = "" +
	"\n" +
	"\x0eprotocol.proto\x12\rcommunication\x1a\x1fgoogle/protobuf/timestamp.proto\"\xca\x01\n" +
	"\aMessage\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12\x18\n" +
	"\apackage\x18\x02 \x01(\tR\apackage\x12:\n" +
	"\x06params\x18\x03 \x03(\v2\".communication.Message.ParamsEntryR\x06params\x1aO\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.communication.ValueR\x05value:\x028\x01\"\xc8\x01\n" +
	"\aCommand\x12\x18\n" +
	"\apackage\x18\x01 \x01(\tR\apackage\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12:\n" +
	"\x06params\x18\x03 \x03(\v2\".communication.Command.ParamsEntryR\x06params\x1aO\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.communication.ValueR\x05value:\x028\x01\"f\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12(\n" +
	"\x04data\x18\x03 \x01(\v2\x14.communication.ValueR\x04data\"\xa0\b\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12:\n" +
	"\fstruct_value\x18\x05 \x01(\v2\x15.communication.StructH\x00R\vstructValue\x129\n" +
	"\n" +
	"list_value\x18\x06 \x01(\v2\x18.communication.ListValueH\x00R\tlistValue\x12!\n" +
	"\vbytes_value\x18\a \x01(\fH\x00R\n" +
	"bytesValue\x12E\n" +
	"\x0ecombined_state\x18\b \x01(\v2\x1c.communication.CombinedStateH\x00R\rcombinedState\x12?\n" +
	"\fospf_metrics\x18\t \x01(\v2\x1a.communication.OSPFMetricsH\x00R\vospfMetrics\x12B\n" +
	"\rospf_neighbor\x18\n" +
	" \x01(\v2\x1b.communication.OSPFNeighborH\x00R\fospfNeighbor\x129\n" +
	"\n" +
	"ospf_route\x18\v \x01(\v2\x18.communication.OSPFRouteH\x00R\tospfRoute\x12E\n" +
	"\x0eospf_interface\x18\f \x01(\v2\x1c.communication.OSPFInterfaceH\x00R\rospfInterface\x123\n" +
	"\bospf_lsa\x18\r \x01(\v2\x16.communication.OSPFlsaH\x00R\aospfLsa\x12E\n" +
	"\x0enetwork_config\x18\x0e \x01(\v2\x1c.communication.NetworkConfigH\x00R\rnetworkConfig\x126\n" +
	"\tospf_area\x18\x0f \x01(\v2\x17.communication.OSPFAreaH\x00R\bospfArea\x12X\n" +
	"\x15ospf_interface_config\x18\x10 \x01(\v2\".communication.OSPFInterfaceConfigH\x00R\x13ospfInterfaceConfig\x12E\n" +
	"\x0esystem_metrics\x18\x11 \x01(\v2\x1c.communication.SystemMetricsH\x00R\rsystemMetrics\x12H\n" +
	"\x0finterface_stats\x18\x12 \x01(\v2\x1d.communication.InterfaceStatsH\x00R\x0einterfaceStatsB\x06\n" +
	"\x04kind\"\x94\x01\n" +
	"\x06Struct\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.communication.Struct.FieldsEntryR\x06fields\x1aO\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.communication.ValueR\x05value:\x028\x01\"9\n" +
	"\tListValue\x12,\n" +
	"\x06values\x18\x01 \x03(\v2\x14.communication.ValueR\x06values\"\xe5\x01\n" +
	"\rCombinedState\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12.\n" +
	"\x04ospf\x18\x02 \x01(\v2\x1a.communication.OSPFMetricsR\x04ospf\x124\n" +
	"\x06config\x18\x03 \x01(\v2\x1c.communication.NetworkConfigR\x06config\x124\n" +
	"\x06system\x18\x04 \x01(\v2\x1c.communication.SystemMetricsR\x06system\"\x90\x02\n" +
	"\vOSPFMetrics\x129\n" +
	"\tneighbors\x18\x01 \x03(\v2\x1b.communication.OSPFNeighborR\tneighbors\x120\n" +
	"\x06routes\x18\x02 \x03(\v2\x18.communication.OSPFRouteR\x06routes\x12<\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\x1c.communication.OSPFInterfaceR\n" +
	"interfaces\x12*\n" +
	"\x04lsas\x18\x04 \x03(\v2\x16.communication.OSPFlsaR\x04lsas\x12*\n" +
	"\x11has_route_changes\x18\x05 \x01(\bR\x0fhasRouteChanges\"v\n" +
	"\fOSPFNeighbor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tinterface\x18\x04 \x01(\tR\tinterface\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\"\x98\x01\n" +
	"\tOSPFRoute\x12\x16\n" +
	"\x06prefix\x18\x01 \x01(\tR\x06prefix\x12\x19\n" +
	"\bnext_hop\x18\x02 \x01(\tR\anextHop\x12\x1c\n" +
	"\tinterface\x18\x03 \x01(\tR\tinterface\x12\x12\n" +
	"\x04cost\x18\x04 \x01(\x05R\x04cost\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x12\n" +
	"\x04area\x18\x06 \x01(\tR\x04area\"\x87\x01\n" +
	"\rOSPFInterface\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\x12\x1b\n" +
	"\tnbr_count\x18\x03 \x01(\x05R\bnbrCount\x12\x17\n" +
	"\anbr_adj\x18\x04 \x01(\x05R\x06nbrAdj\x12\x18\n" +
	"\apassive\x18\x05 \x01(\bR\apassive\"w\n" +
	"\aOSPFlsa\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x13\n" +
	"\x05ls_id\x18\x02 \x01(\tR\x04lsId\x12\x1d\n" +
	"\n" +
	"adv_router\x18\x03 \x01(\tR\tadvRouter\x12\x10\n" +
	"\x03age\x18\x04 \x01(\x05R\x03age\x12\x12\n" +
	"\x04area\x18\x05 \x01(\tR\x04area\"\x9f\x01\n" +
	"\rNetworkConfig\x12\x1b\n" +
	"\trouter_id\x18\x01 \x01(\tR\brouterId\x12-\n" +
	"\x05areas\x18\x02 \x03(\v2\x17.communication.OSPFAreaR\x05areas\x12B\n" +
	"\n" +
	"interfaces\x18\x03 \x03(\v2\".communication.OSPFInterfaceConfigR\n" +
	"interfaces\"6\n" +
	"\bOSPFArea\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnetworks\x18\x02 \x03(\tR\bnetworks\"\x89\x01\n" +
	"\x13OSPFInterfaceConfig\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04area\x18\x02 \x01(\tR\x04area\x12\x1c\n" +
	"\tIpAddress\x18\x03 \x01(\tR\tIpAddress\x12\x18\n" +
	"\apassive\x18\x04 \x01(\bR\apassive\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x05R\x04cost\"\x93\x01\n" +
	"\rSystemMetrics\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12!\n" +
	"\fmemory_usage\x18\x02 \x01(\x01R\vmemoryUsage\x12B\n" +
	"\rnetwork_stats\x18\x03 \x03(\v2\x1d.communication.InterfaceStatsR\fnetworkStats\"\xb3\x01\n" +
	"\x0eInterfaceStats\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\brx_bytes\x18\x02 \x01(\x04R\arxBytes\x12\x19\n" +
	"\btx_bytes\x18\x03 \x01(\x04R\atxBytes\x12\x1b\n" +
	"\trx_errors\x18\x04 \x01(\x04R\brxErrors\x12\x1b\n" +
	"\ttx_errors\x18\x05 \x01(\x04R\btxErrors\x12\x1d\n" +
	"\n" +
	"oper_state\x18\x06 \x01(\tR\toperStateB2Z0github.com/ba2025-ysmprc/frr-tui/backend/pkg;pkgb\x06proto3"

var (
	file_protocol_proto_rawDescOnce sync.Once
	file_protocol_proto_rawDescData []byte
)

func file_protocol_proto_rawDescGZIP() []byte {
	file_protocol_proto_rawDescOnce.Do(func() {
		file_protocol_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)))
	})
	return file_protocol_proto_rawDescData
}

var file_protocol_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_protocol_proto_goTypes = []any{
	(*Message)(nil),               // 0: communication.Message
	(*Command)(nil),               // 1: communication.Command
	(*Response)(nil),              // 2: communication.Response
	(*Value)(nil),                 // 3: communication.Value
	(*Struct)(nil),                // 4: communication.Struct
	(*ListValue)(nil),             // 5: communication.ListValue
	(*CombinedState)(nil),         // 6: communication.CombinedState
	(*OSPFMetrics)(nil),           // 7: communication.OSPFMetrics
	(*OSPFNeighbor)(nil),          // 8: communication.OSPFNeighbor
	(*OSPFRoute)(nil),             // 9: communication.OSPFRoute
	(*OSPFInterface)(nil),         // 10: communication.OSPFInterface
	(*OSPFlsa)(nil),               // 11: communication.OSPFlsa
	(*NetworkConfig)(nil),         // 12: communication.NetworkConfig
	(*OSPFArea)(nil),              // 13: communication.OSPFArea
	(*OSPFInterfaceConfig)(nil),   // 14: communication.OSPFInterfaceConfig
	(*SystemMetrics)(nil),         // 15: communication.SystemMetrics
	(*InterfaceStats)(nil),        // 16: communication.InterfaceStats
	nil,                           // 17: communication.Message.ParamsEntry
	nil,                           // 18: communication.Command.ParamsEntry
	nil,                           // 19: communication.Struct.FieldsEntry
	(*timestamppb.Timestamp)(nil), // 20: google.protobuf.Timestamp
}
var file_protocol_proto_depIdxs = []int32{
	17, // 0: communication.Message.params:type_name -> communication.Message.ParamsEntry
	18, // 1: communication.Command.params:type_name -> communication.Command.ParamsEntry
	3,  // 2: communication.Response.data:type_name -> communication.Value
	4,  // 3: communication.Value.struct_value:type_name -> communication.Struct
	5,  // 4: communication.Value.list_value:type_name -> communication.ListValue
	6,  // 5: communication.Value.combined_state:type_name -> communication.CombinedState
	7,  // 6: communication.Value.ospf_metrics:type_name -> communication.OSPFMetrics
	8,  // 7: communication.Value.ospf_neighbor:type_name -> communication.OSPFNeighbor
	9,  // 8: communication.Value.ospf_route:type_name -> communication.OSPFRoute
	10, // 9: communication.Value.ospf_interface:type_name -> communication.OSPFInterface
	11, // 10: communication.Value.ospf_lsa:type_name -> communication.OSPFlsa
	12, // 11: communication.Value.network_config:type_name -> communication.NetworkConfig
	13, // 12: communication.Value.ospf_area:type_name -> communication.OSPFArea
	14, // 13: communication.Value.ospf_interface_config:type_name -> communication.OSPFInterfaceConfig
	15, // 14: communication.Value.system_metrics:type_name -> communication.SystemMetrics
	16, // 15: communication.Value.interface_stats:type_name -> communication.InterfaceStats
	19, // 16: communication.Struct.fields:type_name -> communication.Struct.FieldsEntry
	3,  // 17: communication.ListValue.values:type_name -> communication.Value
	20, // 18: communication.CombinedState.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 19: communication.CombinedState.ospf:type_name -> communication.OSPFMetrics
	12, // 20: communication.CombinedState.config:type_name -> communication.NetworkConfig
	15, // 21: communication.CombinedState.system:type_name -> communication.SystemMetrics
	8,  // 22: communication.OSPFMetrics.neighbors:type_name -> communication.OSPFNeighbor
	9,  // 23: communication.OSPFMetrics.routes:type_name -> communication.OSPFRoute
	10, // 24: communication.OSPFMetrics.interfaces:type_name -> communication.OSPFInterface
	11, // 25: communication.OSPFMetrics.lsas:type_name -> communication.OSPFlsa
	13, // 26: communication.NetworkConfig.areas:type_name -> communication.OSPFArea
	14, // 27: communication.NetworkConfig.interfaces:type_name -> communication.OSPFInterfaceConfig
	16, // 28: communication.SystemMetrics.network_stats:type_name -> communication.InterfaceStats
	3,  // 29: communication.Message.ParamsEntry.value:type_name -> communication.Value
	3,  // 30: communication.Command.ParamsEntry.value:type_name -> communication.Value
	3,  // 31: communication.Struct.FieldsEntry.value:type_name -> communication.Value
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_protocol_proto_init() }
func file_protocol_proto_init() {
	if File_protocol_proto != nil {
		return
	}
	file_protocol_proto_msgTypes[3].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_IntValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StructValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_CombinedState)(nil),
		(*Value_OspfMetrics)(nil),
		(*Value_OspfNeighbor)(nil),
		(*Value_OspfRoute)(nil),
		(*Value_OspfInterface)(nil),
		(*Value_OspfLsa)(nil),
		(*Value_NetworkConfig)(nil),
		(*Value_OspfArea)(nil),
		(*Value_OspfInterfaceConfig)(nil),
		(*Value_SystemMetrics)(nil),
		(*Value_InterfaceStats)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_proto_rawDesc), len(file_protocol_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_proto_goTypes,
		DependencyIndexes: file_protocol_proto_depIdxs,
		MessageInfos:      file_protocol_proto_msgTypes,
	}.Build()
	File_protocol_proto = out.File
	file_protocol_proto_goTypes = nil
	file_protocol_proto_depIdxs = nil
}
